controller_joint_names: ['', 'link_1', 'link_1_2', 'link_1_2_3', 'wheel_1', 'link_2', 'link_2_2', 'link_2_2_3', 'wheel_2', 'link_3', 'link_3_2', 'link_3_2_3', 'wheel_3', 'link_4', 'link_4_2', 'link_4_2_3', 'wheel_4', ]
